name: Patch Mikrotik RouterOS
on:
  # push:
  #   branches: [ "main" ]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
permissions:
  contents: write

jobs:
  Patch_Latest_RouterOS:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        branch: [7]
        channel: [stable]
    env:
      TZ: 'Asia/Dhaka'
      LATEST7_VERSION_URL: 'https://upgrade.mikrotik.com/routeros/NEWESTa7'
      LATEST6_VERSION_URL: 'http://upgrade.mikrotik.com/routeros/LATEST.6'
      MIKRO_NPK_SIGN_PUBLIC_KEY: C293CED638A2A33C681FC8DE98EE26C54EADC5390C2DFCE197D35C83C416CF59
      MIKRO_LICENSE_PUBLIC_KEY: 8E1067E4305FCDC0CFBF95C10F96E5DFE8C49AEF486BD1A4E2E96C27F01E3E32
      CUSTOM_NPK_SIGN_PRIVATE_KEY: 7D008D9B80B036FB0205601FEE79D550927EBCA937B7008CC877281F2F8AC640
      CUSTOM_NPK_SIGN_PUBLIC_KEY: 28F886E32C141123126CFBCAD56766E99D1720CEB1F12BE2468BEBE7662FBEDB
      CUSTOM_LICENSE_PRIVATE_KEY: 9DBC845E9018537810FDAE62824322EEE1B12BAD81FCA28EC295FB397C61CE0B
      CUSTOM_LICENSE_PUBLIC_KEY: 723A34A6E3300F23E4BAA06156B9327514AEC170732655F16E04C17928DD770F
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' 

    - name: Cache Squashfs
      id: cache-squashfs
      uses: actions/cache@v4
      with:
        path: |
          python3.sfs
          option.sfs
        key: busybox-python3-squashfs

    - name: Create Squashfs for option and python3
      if: steps.cache-squashfs.outputs.cache-hit != 'true'
      run: |
        sudo wget -O bash -nv https://busybox.net/downloads/binaries/1.31.0-i686-uclibc/busybox_ASH
        sudo wget -O busybox -nv https://busybox.net/downloads/binaries/1.31.0-i686-uclibc/busybox
        sudo chmod +x busybox
        sudo chmod +x bash
        sudo mkdir -p ./option-root/bin/
        sudo mv busybox ./option-root/bin/
        sudo mv bash ./option-root/bin/
        COMMANDS=$(./option-root/bin/busybox --list)
        for cmd in $COMMANDS; do
            sudo ln -sf /pckg/option/bin/busybox ./option-root/bin/$cmd
        done
        sudo mksquashfs option-root option.sfs -quiet -comp xz -no-xattrs -b 256k
        sudo rm -rf option-root
        sudo wget -O cpython-3.11.9.tar.gz -nv https://github.com/indygreg/python-build-standalone/releases/download/20240415/cpython-3.11.9+20240415-x86_64-unknown-linux-musl-install_only.tar.gz
        sudo tar -xf cpython-3.11.9.tar.gz
        sudo rm cpython-3.11.9.tar.gz
        sudo rm -rf ./python/include
        sudo rm -rf ./python/share
        sudo mksquashfs python python3.sfs -quiet -comp xz -no-xattrs -b 256k
        sudo rm -rf python

    - name: Get latest routeros version  
      run: |
        echo $(uname -a)
        7.14.3=$(wget -nv -O - ${{ env.LATEST7_VERSION_URL }}.${{ matrix.channel }} | cut -d ' ' -f1)
        echo Latest Version:$7.14.3
        wget -nv -O CHANGELOG.txt https://upgrade.mikrotik.com/routeros/$7.14.3/CHANGELOG
        cat CHANGELOG.txt
        echo "7.14.3=${7.14.3}" >> $GITHUB_ENV

    - name: Cache Mikrotik ${{ env.7.14.3 }}
      id: cache-mikrotik
      uses: actions/cache@v4
      with:
        path: |
          netinstall.zip
          mikrotik.iso
        key: mikrotik-${{ env.7.14.3 }}

    - name: Get netinstall-${{ env.7.14.3 }}.zip and mikrotik-${{ env.7.14.3 }}.iso
      if: steps.cache-mikrotik.outputs.cache-hit != 'true'
      run: |
        sudo wget -nv -O netinstall.zip https://download.mikrotik.com/routeros/$7.14.3/netinstall-$7.14.3.zip
        sudo wget -nv -O mikrotik.iso https://download.mikrotik.com/routeros/$7.14.3/mikrotik-$7.14.3.iso

    - name: Patch netinstall.exe
      run: |
        sudo unzip netinstall.zip
        sudo -E python3 patch.py netinstall netinstall.exe
        sudo zip netinstall-$7.14.3.zip ./netinstall.exe

    - name: Patch mikrotik-${{ env.7.14.3 }}.iso
      run: |
        sudo apt-get install -y mkisofs > /dev/null
        sudo mkdir ./iso 
        sudo mount -o loop,ro mikrotik.iso ./iso
        sudo mkdir ./new_iso
        sudo cp -r ./iso/* ./new_iso/
        sudo rsync -a ./iso/ ./new_iso/
        sudo umount ./iso
        sudo rm -rf ./iso
        sudo mv ./new_iso/routeros-$7.14.3.npk ./
        sudo -E python3 patch.py npk routeros-$7.14.3.npk
        sudo cp keygen.zip ./new_iso/
        NPK_FILES=$(find ./new_iso/*.npk)
        for file in $NPK_FILES; do
            sudo -E python3 npk.py sign $file $file
        done
        sudo cp routeros-$7.14.3.npk ./new_iso/
        sudo -E python3 npk.py create ./new_iso/gps-$7.14.3.npk ./option-$7.14.3.npk option ./option.sfs -desc="busybox and ash"
        sudo cp option-$7.14.3.npk ./new_iso/
        sudo -E python3 npk.py create ./new_iso/gps-$7.14.3.npk ./python3-$7.14.3.npk python3 ./python3.sfs -desc="python 3.11.9"
        sudo cp python3-$7.14.3.npk ./new_iso/
        sudo cp linux ./new_iso/isolinux/
        sudo mkdir ./efiboot
        sudo mount -o loop ./new_iso/efiboot.img ./efiboot
        sudo cp linux ./efiboot/linux.x86_64
        sudo umount ./efiboot
        sudo rm -rf ./efiboot
        sudo mkisofs -o mikrotik-$7.14.3.iso \
                    -V "MikroTik $7.14.3 Patched" \
                    -sysid "" -preparer "MiKroTiK" \
                    -publisher "" -A "MiKroTiK RouterOS" \
                    -b isolinux/isolinux.bin \
                    -c isolinux/boot.cat \
                    -no-emul-boot \
                    -boot-load-size 4 \
                    -boot-info-table \
                    -eltorito-alt-boot \
                    -e efiboot.img \
                    -no-emul-boot \
                    -R -J \
                    ./new_iso

        cd ./new_iso
        sudo zip ../all_packages-x86-$7.14.3.zip *.npk
        cd ..

    - name: Cache refind
      id: cache-refind
      uses: actions/cache@v4
      with:
        path: refind-bin-0.14.2.zip
        key: refind

    - name: Get refind
      if: steps.cache-refind.outputs.cache-hit != 'true'
      run: sudo wget -nv -O refind-bin-0.14.2.zip https://nchc.dl.sourceforge.net/project/refind/0.14.2/refind-bin-0.14.2.zip

    - name: Create install-image-${{ env.7.14.3 }}.img
      run: |
        sudo modprobe nbd
        sudo apt-get update
        sudo apt-get install -y qemu-utils extlinux > /dev/null
        sudo xxd -p -u /usr/bin/extlinux | tr -d '\n' | sed  \
          -e 's/0D0A5359534C494E555820362E30342000/4C6F6164696E672073797374656D0D0A00/g' \
          -e 's/20436F707972696768742028432920313939342D3230313520482E20506574657220416E76696E20657420616C0D0A/00436F707972696768742028432920313939342D3230313520482E20506574657220416E76696E20657420616C0D0A/g' \
          -e 's/203230323130383131/003230323130383131/g' \
          -e 's/43485300454444/00485300004444/g' | xxd -p -r >extlinux
        sudo chmod +x extlinux
        
        truncate --size 128M install-image-$7.14.3.img
        sudo qemu-nbd -c /dev/nbd0 -f raw install-image-$7.14.3.img
        sudo mkfs.vfat -n "Install" /dev/nbd0
        sudo mkdir ./install
        sudo mount /dev/nbd0 ./install
        sudo mkdir -p ./install/EFI/BOOT
        sudo unzip refind-bin-0.14.2.zip refind-bin-0.14.2/refind/refind_x64.efi
        sudo cp refind-bin-0.14.2/refind/refind_x64.efi ./install/EFI/BOOT/BOOTX64.EFI
        sudo rm -rf refind-bin-0.14.2
        echo -e 'timeout 0\ntextonly\ntextmode 0\nshowtools shutdown, reboot, exit\nmenuentry "Install RouterOS" {\n\tloader /linux\n\toptions "load_ramdisk=1 root=/dev/ram0 -install -hdd"\n}\ndefault_selection /EFI/BOOT/BOOTX64.EFI' \
          > refind.conf
        sudo cp refind.conf ./install/EFI/BOOT/
        sudo rm refind.conf
        sudo ./extlinux --install -H 64 -S 32 ./install/
        echo -e 'default system\nLABEL system\n\tKERNEL linux\n\tAPPEND load_ramdisk=1 -install -hdd' \
          > syslinux.cfg
        sudo cp syslinux.cfg ./install/
        sudo rm syslinux.cfg
        sudo cp linux ./install/
        NPK_FILES=($(find ./new_iso/*.npk))
        for ((i=1; i<=${#NPK_FILES[@]}; i++))
        do
          echo "${NPK_FILES[$i-1]}=>$i.npk" 
          sudo cp ${NPK_FILES[$i-1]} ./install/$i.npk
        done
        sudo cp keygen.zip ./install/
        sudo touch ./install/CHOOSE
        sudo touch ./install/autorun.scr 
        sudo umount /dev/nbd0
        sudo qemu-nbd -d /dev/nbd0
        sudo rm -rf ./install
        sudo zip install-image-$7.14.3.zip ./install-image-$7.14.3.img
        sudo rm ./install-image-$7.14.3.img


    - name: Create chr-${{ env.7.14.3 }}.img
      run: |

        truncate --size 128M chr-$7.14.3.img
        sgdisk --clear --set-alignment=2 \
            --new=1::+32M --typecode=1:8300 --change-name=1:"RouterOS Boot" --attributes=1:set:2 \
            --new=2::-0 --typecode=2:8300 --change-name=2:"RouterOS" \
            --gpttombr=1:2 \
            chr-$7.14.3.img
        dd if=chr-$7.14.3.img of=pt.bin bs=1 count=66 skip=446
        echo -e "\x80" | dd of=pt.bin  bs=1 count=1  conv=notrunc
        sgdisk --mbrtogpt --clear --set-alignment=2 \
            --new=1::+32M --typecode=1:8300 --change-name=1:"RouterOS Boot" --attributes=1:set:2 \
            --new=2::-0 --typecode=2:8300 --change-name=2:"RouterOS" \
            chr-$7.14.3.img
        dd if=mbr.bin of=chr-$7.14.3.img  bs=1 count=446 conv=notrunc
        dd if=pt.bin of=chr-$7.14.3.img  bs=1 count=66 seek=446 conv=notrunc

        sudo qemu-nbd -c /dev/nbd0 -f raw chr-$7.14.3.img
        sudo mkfs.vfat -n "Boot" /dev/nbd0p1
        sudo mkfs.ext4 -F -L "RouterOS"  -m 0 /dev/nbd0p2
        sudo mkdir -p ./img/{boot,routeros}
        sudo mount /dev/nbd0p1 ./img/boot/
        sudo mkdir -p  ./img/boot/{BOOT,EFI/BOOT}
        sudo cp linux ./img/boot/EFI/BOOT/BOOTX64.EFI
        sudo ./extlinux --install  -H 64 -S 32 ./img/boot/BOOT
        echo -e "default system\nlabel system\n\tkernel /EFI/BOOT/BOOTX64.EFI\n\tappend load_ramdisk=1 root=/dev/ram0 quiet" > syslinux.cfg
        sudo cp syslinux.cfg ./img/boot/BOOT/
        sudo rm syslinux.cfg
        sudo umount /dev/nbd0p1
        sudo mount  /dev/nbd0p2 ./img/routeros/
        sudo mkdir -p ./img/routeros/{var/pdb/{system,option},rw/disk,dev,boot}
        sudo cp keygen.zip ./img/routeros/rw/disk/
        sudo cp option-$7.14.3.npk ./img/routeros/var/pdb/option/image
        sudo cp routeros-$7.14.3.npk ./img/routeros/var/pdb/system/image
        sudo mknod ./img/routeros/dev/bootdev b 8 0
        sudo mknod ./img/routeros/dev/bootpart b 8 1
        sudo umount /dev/nbd0p2
        sudo rm -rf ./img
        sudo qemu-nbd -d /dev/nbd0

        sudo qemu-img convert -f raw -O qcow2 chr-$7.14.3.img chr-$7.14.3.qcow2
        sudo qemu-img convert -f raw -O vmdk chr-$7.14.3.img chr-$7.14.3.vmdk
        sudo qemu-img convert -f raw -O vpc chr-$7.14.3.img chr-$7.14.3.vhd
        sudo qemu-img convert -f raw -O vhdx chr-$7.14.3.img chr-$7.14.3.vhdx
        sudo qemu-img convert -f raw -O vdi chr-$7.14.3.img chr-$7.14.3.vdi

        sudo zip chr-$7.14.3.qcow2.zip chr-$7.14.3.qcow2
        sudo zip chr-$7.14.3.vmdk.zip chr-$7.14.3.vmdk
        sudo zip chr-$7.14.3.vhd.zip chr-$7.14.3.vhd
        sudo zip chr-$7.14.3.vhdx.zip chr-$7.14.3.vhdx
        sudo zip chr-$7.14.3.vdi.zip chr-$7.14.3.vdi
        sudo zip chr-$7.14.3.img.zip chr-$7.14.3.img

        sudo rm *.qcow2
        sudo rm *.vmdk
        sudo rm *.vhd
        sudo rm *.vhdx
        sudo rm *.vdi
        sudo rm *.img

    - name: Create Publish Directory
      run: |
        mkdir ./publish
        cp CHANGELOG.txt ./publish/
        cp mikrotik-$7.14.3.iso ./publish/
        cp chr-$7.14.3*.zip ./publish/
        cp netinstall-$7.14.3.zip ./publish/
        cp install-image-$7.14.3.zip ./publish/
        cp all_packages-x86-$7.14.3.zip ./publish/
        cp ./new_iso/*.npk ./publish/

#    - name: Sync files
#      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
#      with:
#        server: ${{ secrets.FTP_SERVER }}
#        username:  ${{ secrets.FTP_USERNAME }}
#        password: ${{ secrets.FTP_PASSWORD }}
#        server-dir: "${{ secrets.FTP_DIRECTORY }}/${{ env.7.14.3 }}/"
#        local-dir: ./publish/
 

    - name: Delete Release tag ${{ env.7.14.3 }}
      run: |
        HEADER="Authorization: token ${{ secrets.GITHUB_TOKEN }}"
        RELEASE_INFO=$(curl -s -H $HEADER https://api.github.com/repos/${{ github.repository }}/releases/tags/$7.14.3)
        RELEASE_ID=$(echo $RELEASE_INFO | jq -r '.id')
        echo "Release ID: $RELEASE_ID"
        if [ "$RELEASE_ID" != "null" ]; then
            curl -X DELETE -H "$HEADER" https://api.github.com/repos/${{ github.repository }}/git/refs/tags/$7.14.3
            echo "Tag $7.14.3 deleted successfully."
            curl -X DELETE -H "$HEADER" https://api.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID
            echo "Release with tag $7.14.3 deleted successfully."
        else
            echo "Release not found for tag: $7.14.3)"
        fi

    - name: Create Release tag ${{ env.7.14.3 }}
      uses: softprops/action-gh-release@v2
      with:
        name: "RouterOS ${{ env.7.14.3 }}"
        body_path: "CHANGELOG.txt"
        tag_name: ${{ env.7.14.3 }}
        make_latest:  ${{ matrix.channel == 'stable' && matrix.branch == 7 }}
        prerelease:  ${{ matrix.channel == 'testing' }}
        files: |
          mikrotik-${{ env.7.14.3 }}.iso
          chr-${{ env.7.14.3 }}*.zip
          netinstall-${{ env.7.14.3 }}.zip
          install-image-${{ env.7.14.3 }}.zip
          routeros-${{ env.7.14.3 }}.npk
          option-${{ env.7.14.3 }}.npk
          all_packages-x86-${{ env.7.14.3 }}.zip
